const ABI = [
	{ inputs: [], stateMutability: "nonpayable", type: "constructor" },
	{
		inputs: [{ internalType: "address", name: "target", type: "address" }],
		name: "AddressEmptyCode",
		type: "error",
	},
	{ inputs: [], name: "ERC1167FailedCreateClone", type: "error" },
	{
		inputs: [
			{ internalType: "address", name: "implementation", type: "address" },
		],
		name: "ERC1967InvalidImplementation",
		type: "error",
	},
	{ inputs: [], name: "ERC1967NonPayable", type: "error" },
	{ inputs: [], name: "FailedInnerCall", type: "error" },
	{ inputs: [], name: "InvalidInitialization", type: "error" },
	{ inputs: [], name: "NotInitializing", type: "error" },
	{
		inputs: [{ internalType: "address", name: "owner", type: "address" }],
		name: "OwnableInvalidOwner",
		type: "error",
	},
	{
		inputs: [{ internalType: "address", name: "account", type: "address" }],
		name: "OwnableUnauthorizedAccount",
		type: "error",
	},
	{ inputs: [], name: "UUPSUnauthorizedCallContext", type: "error" },
	{
		inputs: [{ internalType: "bytes32", name: "slot", type: "bytes32" }],
		name: "UUPSUnsupportedProxiableUUID",
		type: "error",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: "uint64",
				name: "version",
				type: "uint64",
			},
		],
		name: "Initialized",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "previousOwner",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "newOwner",
				type: "address",
			},
		],
		name: "OwnershipTransferred",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "implementation",
				type: "address",
			},
		],
		name: "Upgraded",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "tokenAddress",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "userAddress",
				type: "address",
			},
			{
				indexed: true,
				internalType: "uint256",
				name: "price",
				type: "uint256",
			},
		],
		name: "deployInscriptionEvent",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "tokenAddress",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "userAddress",
				type: "address",
			},
			{
				indexed: true,
				internalType: "uint256",
				name: "amount",
				type: "uint256",
			},
		],
		name: "mintInscriptionEvent",
		type: "event",
	},
	{
		inputs: [],
		name: "UPGRADE_INTERFACE_VERSION",
		outputs: [{ internalType: "string", name: "", type: "string" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "string", name: "symbol", type: "string" },
			{ internalType: "uint256", name: "totalSupply", type: "uint256" },
			{ internalType: "uint256", name: "perMint", type: "uint256" },
			{ internalType: "uint256", name: "price", type: "uint256" },
		],
		name: "deployInscription",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		name: "deployedTokens",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "initialOwner", type: "address" },
		],
		name: "initialize",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "tokenAddr", type: "address" }],
		name: "mintInscription",
		outputs: [],
		stateMutability: "payable",
		type: "function",
	},
	{
		inputs: [],
		name: "owner",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "proxiableUUID",
		outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "renounceOwnership",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "_tokenAddress", type: "address" },
		],
		name: "setTokenAddress",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "size",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "", type: "address" }],
		name: "tokenDeployUser",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "", type: "address" }],
		name: "tokenPrices",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "", type: "address" }],
		name: "tokenperMint",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
		name: "transferOwnership",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "newImplementation", type: "address" },
			{ internalType: "bytes", name: "data", type: "bytes" },
		],
		name: "upgradeToAndCall",
		outputs: [],
		stateMutability: "payable",
		type: "function",
	},
	{
		inputs: [],
		name: "withdraw",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
];

export default ABI;
